[package]
name = "ethereum-types"
version = "0.3.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/primitives"
description = "Ethereum types"
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[target.'cfg(not(target_env = "sgx"))'.dependencies.serde]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
optional=true

[dependencies]
crunchy = "0.1.5"
ethbloom = { path = "../ethbloom", version = "0.5.0", default-features = false }
ethereum-types-serialize = { version = "0.2.1", path = "../serialize", optional = true }
fixed-hash = { path = "../fixed-hash", version = "0.2", default-features=false }
uint = { path = "../uint", version = "0.2.1", default-features = false }

[features]
default = ["std", "heapsizeof", "serialize"]
std = ["uint/std", "fixed-hash/std", "ethbloom/std"]
heapsizeof = ["uint/heapsizeof", "fixed-hash/heapsizeof", "ethbloom/heapsizeof"]
serialize = ["std", "ethereum-types-serialize", "serde", "ethbloom/serialize"]
use_asm = ["uint/use_asm"]
impl_quickcheck_arbitrary = ["uint/impl_quickcheck_arbitrary", "fixed-hash/impl_quickcheck_arbitrary"]
